name: kiilib_bucket
description: Kii Library - bucket API
author: fkm <fkm@mokelab.com>
homepage: https://github.com/mokelab/KiiLib_Dart_Bucket
repository: https://github.com/mokelab/KiiLib_Dart_Bucket

version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: "^0.12.0+2"
  kiilib_core: "^0.0.1+4"

dev_dependencies:
  test: "^1.5.1"
